matrix:
  include:
    - language: python
      python: 3.6
      script:
      - python -c "print('Hi from Python!')"
    
    - language: cpp
      compiler: gcc
      script:
      - make
      - make Test
